### ISSUE TITLE
Google home timers, custom time format

### ISSUE THREAD

**Issue by Frooodle** [rianadon/timer-bar-card#19] opened 2021-09-05 22:32 UTC
I am trying to setup google home timers with this however their time format is a bit different, i cant show debug info due to some issues but this is attribute data. Any ideas?

entity name is sensor.kitchen_display_timers
state is 2021-09-05T22:27:04+00:00
state attributes are...

next_timer_status: set
timers:
  - timer_id: timer/xx-xx-xx-xxx-xx
    fire_time: 1630880824
    local_time: '2021-09-05 22:27:04'
    local_time_iso: '2021-09-05T22:27:04+00:00'
    duration: '0:20:00'
    status: set
    label: null
    
integration: google_home
friendly_name: Kitchen display timers
icon: mdi:timer-sand
device_class: timestamp

Only mention of a start time i can see here is from update time values or from doing end minus duration since in example above
fire time (epoch) and local times all have the end time of the timer
![image](https://user-images.githubusercontent.com/77850077/132143119-e6bdff60-c998-4f42-9032-c3a7556620bc.png)

**Comment by rianadon** [comment] 2021-09-06 17:59
This looks like a duplicate of #18, so I'm going to close this one and move discussion there!

**Comment by Frooodle** [comment] 2021-09-06 18:00
@rianadon I first posted in that ticket but the difference was timer vs alarm so i moved to a new ticket instead since some attributes were different, but i guess its same enough..

**Comment by rianadon** [comment] 2021-09-06 18:02
Oh sorry my bad I didn't see the distinction. I'll reopen!

**Comment by rianadon** [comment] 2021-09-06 18:03
For the timer, I see you have both a `duration` and `local_time_iso` atrributes. Do using those as the `duration` and `end_time` properties respectively work?

**Comment by gmcaesar** [comment] 2021-09-07 18:14
I just tried this cause I'd like this too, but I get an error showing "cannot use "in" operator to search for "fixed" in local_time_iso"

Config:

type: custom:timer-bar-card
entity: sensor.kitchen_speaker_timers
end_time: local_time_iso
duration: duration
guess_mode: 'yes'

**Comment by Frooodle** [comment] 2021-09-07 20:15
finally got debug info now with config
type: custom:timer-bar-card
entity: sensor.kitchen_display_timers
end_time:
  attribute: local_time_iso
duration:
  attribute: duration
guess_mode: true
debug: true


debug info is
State: 2021-09-07T20:24:13+00:00 (state mode = idle)
Mode: idle (auto mode = N/A, used)
Duration: second
Time remaining:
Counter:
Attr: {"next_timer_status":"set","timers":[{"timer_id":"timer/xxxx-xxx-xx-xxx","fire_time":1631046253,"local_time":"2021-09-07 20:24:13","local_time_iso":"2021-09-07T20:24:13+00:00","duration":"0:10:00","status":"set","label":null}],"integration":"google_home","friendly_name":"Kitchen display timers","icon":"mdi:timer-sand","device_class":"timestamp"}

**Comment by rianadon** [comment] 2021-09-11 22:50
Sorry about the long response time!

@gmcaesar The format for duration is not so simple, due to me trying to support a few different options. The `end_time` and `duration` options take a dictionary, like this: `end_time: { attribute: "local_time_iso" }`.

Making a simpler visual editor for the configuration is on the todo list, but I won't have time for it for a while.


Thank you @Frooodle for the debugging information. I see the problem: there's actually no `local_time_iso` attribute! The `local_time_iso` is inside this `timers` list.

I'm very unfamiliar with these google home timers. Will there ever be more than one? Is this entity supposed to represent a group of timers? Nevertheless the card does not support attributes nested inside attributes at the moment.

**Comment by gmcaesar** [comment] 2021-09-11 23:18
Yes I found that {attribute: } and changed it, and yes there can be more than one timer running at a time

**Comment by rianadon** [comment] 2021-09-12 00:29
If there is potentially more than one timer, I don't think there is any clean way to do this without templates.

The you would have to create a template entity for the first timer, second timer, etc

A nicer method would be creating a new card for a google home timer set entity that embeds the timer bar card, similar to how my opensprinkler card is a special case of timer bar card for sets of sprinkler valves. This isn't something I'd be able to maintain due to my lack of access to Google Home, but if anyone wants to do this I'd gladly help with the initial code.

**Comment by Frooodle** [comment] 2021-09-12 11:24
I see the state value of the timer sensor is that of the last timers local_time_iso, perhaps for a single timer usecase we can pickup that state value for end_time rather than looking inside timers itself if that cant be done?
I dont know about anyone else but i would never use more than one timer anyway

**Comment by rianadon** [comment] 2021-09-12 18:54
Good idea! I'll add an option for using state values.

**Comment by rianadon** [comment] 2021-09-12 19:17
Published in 1.11!

Unfortunately, duration is still embedded within that timer list, so you'll need to either pull it out with a template, or use `duration: { fixed: "0:10:00" }`.

**Comment by gmcaesar** [comment] 2021-09-19 04:16
I have tried a couple of ways to get this working and for some reason no go..... I must be missing something

attempt number one:

type: custom:timer-bar-card
entity: sensor.kitchen_speaker_timers
guess_mode: true
duration:
  entity: input_number.kitchen_timer_duration
  units: minutes
end_time:
  entity: input_datetime.kitchen_timer

where both the end time and duration entities are set by a node red flow that pulls apart the sensor, then I thought maybe the end_time did not support the entity, so I tried this (with both guess mode true and false...):

type: custom:timer-bar-card
entity: input_datetime.kitchen_timer
duration:
  entity: input_number.kitchen_timer_duration
  units: minutes

and both just return the time in a different format.

option one just shows: 2021-09-18T22:08:55-07:00
and option two shows: 10:08 PM

what  is missing?

**Comment by gmcaesar** [comment] 2021-09-19 04:38
found my own anwser - one more entity needed:

type: custom:timer-bar-card
entity: input_boolean.kitchen_timer
icon: mdi:timer
duration:
  entity: input_number.kitchen_timer_duration
  units: minutes
end_time: {{states('input_datetime.kitchen_timer') }}

**Comment by jazzyisj** [comment] 2021-09-21 05:52
@gmcaesar 

Here's a template sensor that works with the Google Home integration and this card.  You'll have to create a template for each Google Home entity you need.  This will only work for the first timer.  You can create additional sensors for multiple timers per google entity by changing` timers[0]` to` timers[1]`,` timers[2] `etc.

```
template:
  - sensor:
      - name: "Dining Room Display Timer"
        unique_id: dining_room_display_timer
        icon: mdi:timer
        state: >
          {% if states.sensor.dining_room_display_timers.attributes.timers[0].status == 'set' %} active
          {% elif states.sensor.dining_room_display_timers.attributes.timers[0].status == 'paused' %} paused
          {% elif states.sensor.dining_room_display_timers.attributes.timers[0].status == 'waiting' %} waiting
          {% else %} idle
          {% endif %}
        attributes:
          duration: "{{ states.sensor.dining_room_display_timers.attributes.timers[0].duration }}"
          end_time: "{{ states.sensor.dining_room_display_timers.attributes.timers[0].local_time_iso }}"
          integration: google_home
        availability: "{{ states('sensor.dining_room_display_timers')|lower not in ['unknown','unavailable','none'] }}"
```
The integration attribute is added so you can easily use an [auto-entities card](https://github.com/thomasloven/lovelace-auto-entities) to display all of your google home timers in a card.

```
type: custom:auto-entities
filter:
  include:
    - domain: sensor
      entity_id: "sensor.*_timer"
      attributes:
        integration: google_home
  exclude:
    - state: unavailable
sort:
  method: name
  ignore_case: true
show_empty: false
card:
  type: custom:timer-bar-card
```
![image](https://user-images.githubusercontent.com/44064559/134113229-3b0994a2-079f-4e2d-bee9-35772cb90fce.png)

**Closed** 2021-09-21 14:45 UTC

**Comment by jazzyisj** [comment] 2021-09-21 21:08
@Frooodle @gmcaesar 
I had to make a little edit to that template.  I didn't realize that the timers attribute is actually an empty list instead of null when there is no timer running.  These changes will kill the warnings in the log.  Small change in the auto_entities card to accomodate this also.

**Comment by SLaks** [comment] 2024-04-19 14:26
See https://github.com/rianadon/timer-bar-card/pull/140#issuecomment-2029064243 for better support
