### ISSUE TITLE
Progress bar reset after resuming from pause in 'sensor' mode

### ISSUE THREAD

**Issue by kalhimeo** [rianadon/timer-bar-card#31] opened 2021-11-29 02:01 UTC
**Describe the bug**
I compared the behaviour of the progress bar after resuming from pause between "timer" and "sensor" entities and I noticed a difference. When a "sensor" entity resumes, the progress bar is reset, while for the "timer" entity the progress bar continues from where is was before the pause (which should be the right behaviour imo). Let's take this example to illustrate :
1) Two cards are showing the progress of a timer of 60s with 17s remaining -> progress bar are similar (normal)
![1 Running](https://user-images.githubusercontent.com/6355373/143797058-84937767-1f40-4532-8295-7b9e78db1891.jpg)
2) The device is paused -> progress bar is hidden (normal)
![2 Paused](https://user-images.githubusercontent.com/6355373/143797246-5d5d9eb4-60a3-4f6f-a7c6-b5b1fbdab558.jpg)
3) The device is unpaused, timers are running again -> progress bar of the "sensor entity" is restarting from 0 while the progress bar of the "timer entity" is picking up where is stopped before the pause.
![3 Resumed](https://user-images.githubusercontent.com/6355373/143797359-72413b31-2d53-42ac-aa7a-3413eab01b61.jpg)

**Your card configuration**
```yaml
type: custom:timer-bar-card
entities:
  - entity: sensor.four_micro_ondes_operation_state
active_state:
  - Run
pause_state:
  - Pause
end_time:
  entity: sensor.four_micro_ondes_remaining_program_time
  state: true
debug: true

type: custom:timer-bar-card
entities:
  - entity: timer.four_micro_ondes
debug: true
```

**Debug information**
See screenshots above

**Comment by rianadon** [comment] 2021-11-29 02:13
Great report! This is, however, the expected behavior from your configuration.

The card only has the end time of the sensor to use for drawing the progress bar, so it must take a guess at how much time has progressed. With the pausing, this guess in inaccurate.

If you have the data, I'd suggest setting the `duration` property, and that should fix the problem.

**Comment by kalhimeo** [comment] 2021-11-29 02:23
Thanks for the explanations, now that you say that it totally makes sense ! sorry for the disturbances :p

**Comment by rianadon** [comment] 2021-12-20 23:04
I'm closing this issue since it looks like you've figured things out. Please reopen if the card is still having trouble!

**Closed by rianadon** 2021-12-20 23:04 UTC
